return {     
["aa"] = "[[File:Ind-artifact.png|25px|alt=Alien Artifact|link=Alien Artifact]][[Alien Artifact|ar]]",
["ar"] = "[[File:Ind-relic.png|25px|alt=Alien Relic|link=Alien Relic]][[Alien Relic|rl]]",
["al"] = "[[File:Ind-aluminum.png|25px|alt=Aluminum|link=Aluminum]][[Aluminum|al]]",
["ai"] = "[[File:Ind-instructions.png|25px|alt=Ancient Instructions|link=Ancient Instructions]][[Ancient Instructions|in]]",
["atn"] = "[[File:Ind-antanium.png|25px|alt=Antanium|link=Antanium]][[Antanium|an]]",
["atr"] = "[[File:Ind-antaura.png|25px|alt=Antaura|link=Antaura]][[Antaura|aa]]",
["anp"] = "[[File:Ind-antpaste.png|25px|alt=Ant Paste|link=Ant Paste]][[Ant Paste|ap]]",
["air"] = "[[File:Ind-air.png|25px|alt=Atmosphere|link=Atmosphere]][[Atmosphere|a]]",
["bri"] = "[[File:Ind-bricks.png|25px|alt=Bricks|link=Bricks]][[Bricks|b]]",
["cha"] = "[[File:Ind-charcoal.png|25px|alt=Charcoal|link=Charcoal]][[Charcoal|ch]]",
["civ"] = "[[File:Ind-civic.png|25px|alt=Civics|link=Civics]][[Civics|c]]",
["cla"] = "[[File:Ind-clay.png|25px|alt=Clay|link=Clay]][[Clay|c]]",
["clo"] = "[[File:Ind-cloth.png|25px|alt=Cloth|link=Cloth]][[Cloth|cl]]",
["cob"] = "[[File:Ind-cobalt.png|25px|alt=Cobalt|link=Cobalt]][[Cobalt|co]]",
["cry"] = "[[File:Ind-crystal.png|25px|alt=Crystalline|link=Crystalline]][[Crystalline|cr]]",
["dia"] = "[[File:Ind-diamond.png|25px|alt=Diamond|link=Diamond]][[Diamond|di]]",
["eth"] = "[[File:Ind-ether.png|25px|alt=Ether (Resources)|link=Ether (Resources)]][[Ether (Resources)|et]]",
["fsh"] = "[[File:Ind-zoology.png|25px|alt=Fish|link=Fish]][[Fish|fi]]",
["fod"] = "[[File:Ind-food.png|25px|alt=Food|link=Food]][[Food|f]]",
["gld"] = "[[File:Ind-gold.png|25px|alt=Gold|link=Gold]][[Gold|g]]",
["he3"] = "[[File:Ind-he3.png|25px|alt=Helium 3|link=Helium 3]][[Helium 3|he]]",
["mcc"] = "[[File:Ind-microchip.png|25px|alt=Microchip|link=Microchip]][[Microchip|m]]",
["mon"] = "[[File:Ind-coin.png|25px|alt=Money|link=Money]][[Money|$]]",
["nn"] = "[[File:Nanotech.png|25px|alt=Nanite|link=Nanite]][[Nanite|na]]",
["obs"] = "[[File:Ind-obsidian.png|25px|alt=Obsidian|link=Obsidian]][[Obsidian|on]]",
["oil"] = "[[File:Ind-oil.png|25px|alt=Oil|link=Oil]][[Oil|oi]]",
["ore"] = "[[File:Ind-ore.png|25px|alt=Ore|link=Ore]][[Ore|o]]",
["pat"] = "[[File:Ind-painting.png|25px|alt=Painting|link=Painting]][[Painting|pa]]",
["pla"] = "[[File:Ind-plastic.png|25px|alt=Plastic|link=Plastic]][[Plastic|p]]",
["pot"] = "[[File:Ind-pottery.png|25px|alt=Pottery|link=Pottery]][[Pottery|p]]",
["rgl"] = "[[File:Ind-regolith.png|25px|alt=Regolith|link=Regolith]][[Regolith|re]]",
["res"] = "[[File:Ind-research.png|25px|alt=Research|link=Research]][[Research|r]]",
["rob"] = "[[File:Ind-robot.png|25px|alt=Robot|link=Robot]][[Robot|ro]]",
["rum"] = "[[File:Ind-rum.png|25px|alt=Rum|link=Rum]][[Rum|ru]]",
["saw"] = "[[File:Ind-saltwater.png|25px|alt=Salt Water|link=Salt Water]][[Salt Water|sa]]",
["sfw"] = "[[File:Ind-software.png|25px|alt=Software|link=Software]][[Software|sw]]",
["ss"] = "[[File:Ind-starship.png|25px|alt=Starship|link=Starship]][[Starship|ss]]",
["ste"] = "[[File:Ind-steel.png|25px|alt=Steel|link=Steel]][[Steel|s]]",
["sug"] = "[[File:Ind-sugar.png|25px|alt=Sugar|link=Sugar]][[Sugar|s]]",
["toy"] = "[[File:Ind-toy.png|25px|alt=Toy|link=Toy]][[Toy|t]]",
["tra"] = "[[File:Ind-trash.png|25px|alt=Trash|link=Trash]][[Trash|tr]]",
["tri"] = "[[File:Ind-triantanium.png|25px|alt=Triantanium|link=Triantanium]][[Triantanium|ta]]",
["ura"] = "[[File:Ind-uranium.png|25px|alt=Uranium|link=Uranium]][[Uranium|u]]",
["wat"] = "[[File:Ind-water.png|25px|alt=Water|link=Water]][[Water|w]]",
["whe"] = "[[File:Ind-wheel.png|25px|alt=Wheel|link=Wheel]][[Wheel|wh]]",
["wod"] = "[[File:Ind-wood.png|25px|alt=Wood|link=Wood]][[Wood|wo]]",
["wol"] = "[[File:Ind-wool.png|25px|alt=Wool|link=Wool]][[Wool|wl]]",
["Alien Artifact"] = "[[File:Ind-artifact.png|25px|alt=Alien Artifact|link=Alien Artifact]][[Alien Artifact|ar]]",
["Alien Relic"] = "[[File:Ind-relic.png|25px|alt=Alien Relic|link=Alien Relic]][[Alien Relic|rl]]",
["Aluminum"] = "[[File:Ind-aluminum.png|25px|alt=Aluminum|link=Aluminum]][[Aluminum|al]]",
["Ancient Instructions"] = "[[File:Ind-instructions.png|25px|alt=Ancient Instructions|link=Ancient Instructions]][[Ancient Instructions|in]]",
["Antanium"] = "[[File:Ind-antanium.png|25px|alt=Antanium|link=Antanium]][[Antanium|an]]",
["Antaura"] = "[[File:Ind-antaura.png|25px|alt=Antaura|link=Antaura]][[Antaura|aa]]",
["Ant Paste"] = "[[File:Ind-antpaste.png|25px|alt=Ant Paste|link=Ant Paste]][[Ant Paste|ap]]",
["Atmosphere"] = "[[File:Ind-air.png|25px|alt=Atmosphere|link=Atmosphere]][[Atmosphere|a]]",
["Bricks"] = "[[File:Ind-bricks.png|25px|alt=Bricks|link=Bricks]][[Bricks|b]]",
["Charcoal"] = "[[File:Ind-charcoal.png|25px|alt=Charcoal|link=Charcoal]][[Charcoal|ch]]",
["Civics"] = "[[File:Ind-civic.png|25px|alt=Civics|link=Civics]][[Civics|c]]",
["Clay"] = "[[File:Ind-clay.png|25px|alt=Clay|link=Clay]][[Clay|c]]",
["Cloth"] = "[[File:Ind-cloth.png|25px|alt=Cloth|link=Cloth]][[Cloth|cl]]",
["Cobalt"] = "[[File:Ind-cobalt.png|25px|alt=Cobalt|link=Cobalt]][[Cobalt|co]]",
["Crystalline"] = "[[File:Ind-crystal.png|25px|alt=Crystalline|link=Crystalline]][[Crystalline|cr]]",
["Diamond"] = "[[File:Ind-diamond.png|25px|alt=Diamond|link=Diamond]][[Diamond|di]]",
["Ether"] = "[[File:Ind-ether.png|25px|alt=Ether (Resources)|link=Ether (Resources)]][[Ether (Resources)|et]]",
["Fish"] = "[[File:Ind-zoology.png|25px|alt=Fish|link=Fish]][[Fish|fi]]",
["Food"] = "[[File:Ind-food.png|25px|alt=Food|link=Food]][[Food|f]]",
["Gold"] = "[[File:Ind-gold.png|25px|alt=Gold|link=Gold]][[Gold|g]]",
["Helium 3"] = "[[File:Ind-he3.png|25px|alt=Helium 3|link=Helium 3]][[Helium 3|he]]",
["Microchip"] = "[[File:Ind-microchip.png|25px|alt=Microchip|link=Microchip]][[Microchip|m]]",
["Money"] = "[[File:Ind-coin.png|25px|alt=Money|link=Money]][[Money|$]]",
["Nanite"] = "[[File:Nanotech.png|25px|alt=Nanite|link=Nanite]][[Nanite|na]]",
["Obsidian"] = "[[File:Ind-obsidian.png|25px|alt=Obsidian|link=Obsidian]][[Obsidian|on]]",
["Oil"] = "[[File:Ind-oil.png|25px|alt=Oil|link=Oil]][[Oil|oi]]",
["Ore"] = "[[File:Ind-ore.png|25px|alt=Ore|link=Ore]][[Ore|o]]",
["Painting"] = "[[File:Ind-painting.png|25px|alt=Painting|link=Painting]][[Painting|pa]]",
["Plastic"] = "[[File:Ind-plastic.png|25px|alt=Plastic|link=Plastic]][[Plastic|p]]",
["Pottery"] = "[[File:Ind-pottery.png|25px|alt=Pottery|link=Pottery]][[Pottery|p]]",
["Regolith"] = "[[File:Ind-regolith.png|25px|alt=Regolith|link=Regolith]][[Regolith|re]]",
["Research"] = "[[File:Ind-research.png|25px|alt=Research|link=Research]][[Research|r]]",
["Robot"] = "[[File:Ind-robot.png|25px|alt=Robot|link=Robot]][[Robot|ro]]",
["Rum"] = "[[File:Ind-rum.png|25px|alt=Rum|link=Rum]][[Rum|ru]]",
["Salt Water"] = "[[File:Ind-saltwater.png|25px|alt=Salt Water|link=Salt Water]][[Salt Water|sa]]",
["Software"] = "[[File:Ind-software.png|25px|alt=Software|link=Software]][[Software|sw]]",
["Starship"] = "[[File:Ind-starship.png|25px|alt=Starship|link=Starship]][[Starship|ss]]",
["Steel"] = "[[File:Ind-steel.png|25px|alt=Steel|link=Steel]][[Steel|s]]",
["Sugar"] = "[[File:Ind-sugar.png|25px|alt=Sugar|link=Sugar]][[Sugar|s]]",
["Toy"] = "[[File:Ind-toy.png|25px|alt=Toy|link=Toy]][[Toy|t]]",
["Trash"] = "[[File:Ind-trash.png|25px|alt=Trash|link=Trash]][[Trash|tr]]",
["Triantanium"] = "[[File:Ind-triantanium.png|25px|alt=Triantanium|link=Triantanium]][[Triantanium|ta]]",
["Uranium"] = "[[File:Ind-uranium.png|25px|alt=Uranium|link=Uranium]][[Uranium|u]]",
["Water"] = "[[File:Ind-water.png|25px|alt=Water|link=Water]][[Water|w]]",
["Wheel"] = "[[File:Ind-wheel.png|25px|alt=Wheel|link=Wheel]][[Wheel|wh]]",
["Wood"] = "[[File:Ind-wood.png|25px|alt=Wood|link=Wood]][[Wood|wo]]",
["Wool"] = "[[File:Ind-wool.png|25px|alt=Wool|link=Wool]][[Wool|wl]]",
}